### ISSUE TITLE
NoPSN Apps donwloader issue

### ISSUE THREAD

**Issue by ShaolinAssassin** [ShaolinAssassin/HAN-Toolbox#1]
Download works fine but install fails...

**Comment by ShaolinAssassin** [comment]
Working if I download app from dropbox...

**Comment by ShaolinAssassin** [comment]
Hey @pink1stools - any idea why the example below doesn't work ? It downloads fine but install fails (error 80010006). I'm clueless... Thanks !

```
	<View id="nopsn_downloader_EU_crunchyroll_link"> 
		<Attributes> 
			<Table key="nopsn_downloader_EU_crunchyroll_link"> 
				<Pair key="info"><String>net_package_install</String></Pair> 
				<Pair key="pkg_src"><String>http://nopsn.com/pkg/ps3/crunchyroll/Crunchyroll-v1.29-%5BNPEB02307%5D-NoPSN-etHANol.pkg</String></Pair> 
				<Pair key="pkg_src_qa"><String>http://nopsn.com/pkg/ps3/crunchyroll/Crunchyroll-v1.29-%5BNPEB02307%5D-NoPSN-etHANol.pkg</String></Pair> 
				<Pair key="content_name"><String>tool_pkg_install_pc</String></Pair> 
				<Pair key="content_id"><String>EP8805-NPEB02307_00-20150410XCRUNCHY</String></Pair> 
				<Pair key="prod_pict_path"><String>/dev_hdd0/game/HANTOOLBX/USRDIR/IMAGES/nopsn_icons/crunchyroll.png</String></Pair> 
			</Table> 
		</Attributes> 
		<Items> 
			<Item class="type:x-xmb/xmlnpsignup" key="nopsn_downloader_EU_crunchyroll_link" attr="nopsn_downloader_EU_crunchyroll_link"/> 
		</Items> 
	</View> 
```

**Comment by pink1stools** [comment]
@DeViL303 may have an answer. He's the one behind the method I just helped make some tools to speed up making the xml. 
It may be a problem with the pkg name. Here is a quote from the wiki on that error
"ENOENT | 0x80010006 | The file does not exist Note : This error can happen when you try to install a pkg that have an invalid name."
It may be this "%5BNPEB02307%5D" have you tried using it like this "[NPEB02307]"?

**Comment by ShaolinAssassin** [comment]
Thanks for the suggestion, gonna try it ;)

**Comment by pink1stools** [comment]
I can't see anything else wrong with the links so I hope it works. Let me know how it goes.

**Comment by ShaolinAssassin** [comment]
That worked perfectly, thanks a lot !

**Comment by pink1stools** [comment]
Yeah I'm thinking it was trying to find a file named "Crunchyroll-v1.29-%5BNPEB02307%5D-NoPSN-etHANol.pkg" instead of "Crunchyroll-v1.29-[NPEB02307]-NoPSN-etHANol.pkg".  

Anytime bud just ask. If I don't respond send me a pm somewhere so I get an alert I hadn't checked the email that I get notifications from here in over a month & just happened to check it today :)
