### ISSUE TITLE
File Copier 4.82 Compatibility

### ISSUE THREAD

**Issue by siboxd** [ShaolinAssassin/HAN-Toolbox#6]
Is **v0.7.1 FileCopier** compatible with **4.82 console**?? I used to see the supported version below the tool name, but in new version that's gone.

If not can you make the File Copier backwards compatible with 4.82 even in newer version??
So one can update to *Han Toolbox (v0.7.1)* without loosing functionalities staying in 4.82!
Now if one has *v0.7-fixed* version has the double tools with specific usage firmware... but it's prompted to update the above HanToolbox version where FileCopier is all-in-one. I made a fast test and i couldn't copy files (maybe my fault).

Thanks for your attention.

**Comment by ShaolinAssassin** [comment]
Sorry for the late reply, I see your message only now. Yes, file copier in v0.7.1 is 4.84 ompatible only. For a few reasons, I removed the 4.82 one. 
I can't make a 4.82/4.84 compatible one - I'm only collecting them and adding them to Toolbox.
You can either : 
- update to 4.84 (there is no reason to stay on 4.82 - and even less that HEN is out) - 4.84 file copier has a better success rate according to lmn7 (the guy who made it)
- wait for the next Toolbox update (soon, matter of days), as I added the possibility to load custom XML files from USB.
